#!/bin/bash
blk='\e[0;30m' red='\e[0;31m' grn='\e[0;32m' ylw='\e[0;33m'
blu='\e[0;34m' pur='\e[0;35m' cyn='\e[0;36m' wht='\e[0;37m'
clear
case "$1" in
	"")
clear
printf "${blu}Welcome To Debian Termux For Android\n"
printf "${red}> ${wht}https://github.com/wahasa/Debian"
printf "\n\n"
printf "${ylw}• Debian 13 (Trixie)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Debian13\n"
printf "${blu}Version ${red}: ${grn}13.0\n"
printf "${blu}Status  ${red}: ${grn}Pre-release\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Debian 12 (Bookworm)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Debian12\n"
printf "${blu}Version ${red}: ${grn}12.0\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Debian 11 (Bullseye)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Debian11\n"
printf "${blu}Version ${red}: ${grn}11.7\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Debian 10 (Buster)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Debian10\n"
printf "${blu}Version ${red}: ${grn}10.13\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Debian (Development)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}DebianDev\n"
printf "${blu}Version ${red}: ${grn}Beta 13.0\n"
printf "${blu}Code    ${red}: ${grn}Trixie\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "DebianDev")
wget https://raw.githubusercontent.com/wahasa/Debian/main/Install/debian.sh ; chmod +x debian.sh ; bash debian.sh
        ;;
        "Debian13")
wget https://raw.githubusercontent.com/wahasa/Debian/main/Install/debian13.sh ; chmod +x debian13.sh ; bash debian13.sh
        ;;
        "Debian12")
wget https://raw.githubusercontent.com/wahasa/Debian/main/Install/debian12.sh ; chmod +x debian12.sh ; bash debian12.sh
        ;;
        "Debian11")
wget https://raw.githubusercontent.com/wahasa/Debian/main/Install/debian11.sh ; chmod +x debian11.sh ; bash debian11.sh
	;;
        "Debian10")
wget https://raw.githubusercontent.com/wahasa/Debian/main/Install/debian10.sh ; chmod +x debian10.sh ; bash debian10.sh
        ;;
        *)
	bash Install
        ;;
esac
